lib/BUILD
Unclear why this didn't fail in original testing...
=> Fix misspelled testonly attribute

README.md
=> Add "Getting Started" section to README

BUILD, CONTRIBUTORS, lib.bzl, lib/BUILD, lib/partial.bzl, tests/BUILD, tests/partial_tests.bzl
This implements something very similar to partials in Python.
https://docs.python.org/3/library/functools.html#functools.partial
=> Add support for 'functools.partial' like functionality.

lib/types.bzl
Along the lines of the caching done in #62
=> Cache the types to avoid fetching it every time.

lib/BUILD
=> Fix skylark_library deps for new_sets and unittest.

.travis_build.sh
Move the find args into a shell variable to simplify things.
=> Add WORKSPACE to the things checked by buildifier.

rules/maprule_private.bzl
Give the rule is in this repo, it seems like the load should be from this repo.
=> Fix example load directive.

BUILD, rules/BUILD
Likely needed for anyone doing integration tests using skylib.
=> Add rules to the test_deps target.

lib/types.bzl, tests/types_tests.bzl
=> Add `types.is_depset`.

.bazelci/presubmit.yml
Using just "..." makes it appear that the command output is too long and being truncated.
=> Use //... to mean "all packages"

tests/analysis_test_test.sh, tests/unittest_test.sh
Fixes https://github.com/bazelbuild/bazel-skylib/issues/143
=> Use TEST_SRCDIR for shell tests

README.md
Signed-off-by: Christian Blichmann <cblichmann@google.com>
=> README.md: Fix typo in project name

docs/BUILD, docs/common_settings_doc.md, rules/BUILD
Use stardoc to generate documentation for common_settings.bzl
=> Create new stardoc target for common_settings.bzl

rules/common_settings.bzl
I just ran buildifier over the file.
=> Fix some formatting problems.

BUILD, rules/BUILD, rules/private/BUILD, toolchains/unittest/BUILD, version.bzl
unittest toolchains were missing.
=> Fix to 1.0.1 - add missing .bzl files

toolchains/unittest/BUILD
https://github.com/bazelbuild/bazel/issues/8622
=> Migrate for --incompatible_use_platforms_repo_for_constraints

tests/paths_tests.bzl
Add missing Windows absolute path tests.
=> Add absolute path tests for Windows

distribution/BUILD
```
buildifier -lint=fix distribution/BUILD
```
=> Fix buildifier issue failing on CI.

WORKSPACE, internal_setup.bzl, lib/new_sets.bzl, lib/unittest.bzl
Using the 1.0 release.
```
buildifier -r .
```
=> Run buildifier over the directory.

lib/new_sets.bzl
Looking at the impl, it only accepts sets.
=> Fix the comment to match the code.

CODEOWNERS
...so I can maintain the skylib build settings
=> Add juliexxia to codeowners for rules/

lib/unittest.bzl, tests/selects_tests.bzl, tests/unittest_tests.bzl
In https://buildkite.com/bazel/bazel-skylib/builds/1240#annotation-buildifier
I noticed buildifier issues unrelated to my PR.
This PR attempts to address these latent buildifier issues.
Fixes #277
=> Address latent buildifier issues.

docs/partial_doc.md, lib/partial.bzl
For https://github.com/bazelbuild/bazel-skylib/pull/308 I edited the markdown directly. I should've updated the bzl file and generated the documentation.
=> Update partial.bzl to generate better markdown

CHANGELOG.md
=> Update changelog for release 1.1.0

lib/dicts.bzl, tests/dicts_tests.bzl
=> Implement omit and pick dicts functions.

docs/dicts_doc.md
=> Update dicts documentation.

gazelle/bzl/gazelle.go
=> Fixing typo: allocate slice with the correct size

docs/maintainers_guide.md, rules/private/copy_common.bzl
* Fix canonical build encyclopedia url
* Fix path to distribution tarball
=> Documentation fixes

CHANGELOG.md, MODULE.bazel, gazelle/MODULE.bazel, version.bzl
To be merged after https://github.com/bazelbuild/bazel-skylib/pull/433
=> Update changelog and version for release 1.4.1

README.md, docs/expand_template_doc.md, docs/maintainers_guide.md, docs/private/stardoc_with_diff_test.bzl, gazelle/bzl/gazelle.go, gazelle/bzl/testdata/README.md, gazelle/bzl/testdata/empty/BUILD.in, rules/expand_template.bzl, tests/diff_test/diff_test_tests.sh, tests/selects_tests.bzl, tests/unittest.bash
=> Fix spelling

tests/analysis_test_test.sh
Fixes https://github.com/bazelbuild/bazel-skylib/issues/458
=> Fix bazel-skylib with Bazel@HEAD

rules/private/copy_directory_private.bzl
The same as https://github.com/bazelbuild/bazel-skylib/pull/455.
=> Modify actions in order not to need toolchain param

rules/BUILD, rules/private/BUILD
This pattern was missed when rules/private was added.
=> Add test_deps to rules/private

tests/diff_test/diff_test_tests.sh, tests/unittest_test.sh
Fixes https://github.com/bazelbuild/bazel-skylib/issues/537
=> Fix bazel_skylib with Bazel@HEAD

.bazelci/presubmit.yml
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4122#0191e992-e9e6-4d90-8662-7f5ef3aedd10
Fixes https://github.com/bazelbuild/bazel-skylib/issues/539
=> Explicitly enable workspace for some tasks
