bazelbuild/bazel-skylib

- BUILD
- CONTRIBUTORS
- README.md
- lib/BUILD
- skylark_library.bzl
Adding a `skylark_library` target for rules files suitable for use in Python-interpretation-based unit tests, as well as a parent target for [Skydoc doc generation](https://skydoc.bazel.build/)'s `skydoc_library`.
> Skylark library

- CONTRIBUTORS
- README.md
- lib.bzl
- lib/versions.bzl
- tests/BUILD
- tests/versions_tests.bzl
Allows users to set a minimum and maximum Bazel version that their rules can build with. This can become the canonical version of version checking (see https://github.com/bazelbuild/bazel/issues/4433)
e.g. 
```py
load("@bazel_skylib//:lib.bzl", "versions")
versions.check(minimum_bazel_version = "0.4.5", maximum_bazel_version = "1.0.0") # fails if not within range
```
There are no tests for failure cases until we have something like `asserts.failure(env, msg, call`)
Test results:
```
$ bazel test //...
INFO: Analysed 38 targets (11 packages loaded).
INFO: Found 12 targets and 26 test targets...
INFO: Elapsed time: 0.364s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
//tests:collections_tests_test_0                                (cached) PASSED in 0.1s …
```
> Added a lib for version checking and comparison

- lib/versions.bzl
_check_bazel_version prints a warning in this case, but then attempts
to parse and check None. It should return early.
> versions.bzl: skip check if native.bazel_version is None

- .travis.yml
- .travis_build.sh
- .travis_install.sh
- Move install into a stand alone script to expand it.
- Support installing the latest bazel release.
- Move the script step into a stand along script to expand it.
- Support doing a build or running buildifier.
- Update the config to:
- Use the latest bazel release and head for tests (won't have
to update the config with each bazel release).
- Add a buildifer test to ensure the files are good.
> Travis improvements.

- .bazelci/presubmit.yml
- README.md
we'll run skylib as a postsubmit project and
before every release to ensure we don't break
it.
> add buildkite to bazel's new ci

- .travis.yml
- .travis_build.sh
- .travis_install.sh
Disable the HEAD build, as we don't have a way to download the bazel
binary at the moment.  bazel.build.ci should provide that instead.
> Travis updates for bazel moving to buildkite.

- .travis.yml
- .travis_install.sh
- Add support for fetch HEAD bazel from their new setup.
- Switch travis to building with HEAD since bazel's ci is using the last release.
> Test HEAD bazel on travis.

- tests/shell_tests.bzl
Be explicit about the file create/to run instead of using
ctx.outputs.executable.
> Skylint: stop using ctx.outputs.executable.

- lib.bzl
- lib/BUILD
- lib/types.bzl
- tests/BUILD
- tests/types_tests.bzl
Even though it's not great to use type checks, they are frequently useful for
checking input types of macros.
Because there is no standard way of checking types, at least 2 types of checks
are used:
- `type(foo) == type([])`
- `type(foo) == "list"`
The first option is not very readable and the second option seem to be relying
on an Bazel implementation detail. Encapsulating type checks into this library
enables consistent and easy to understand type checking without explicitly
relying on implementation details.
There are still more checks to add, but this change creates a scaffold.
> Add type checking functions.

- .travis_build.sh
buildifer 0.12.0 release sets the exit status for diff.
> Update check to use buildifier's exit status instead.

- .travis_build.sh
- lib.bzl
- lib/collections.bzl
- lib/dicts.bzl
- lib/new_sets.bzl
- lib/partial.bzl
- lib/paths.bzl
- lib/selects.bzl
- lib/sets.bzl
- lib/shell.bzl
- lib/structs.bzl
- lib/types.bzl
- lib/unittest.bzl
- lib/versions.bzl
- skylark_library.bzl
- tests/collections_tests.bzl
- tests/dicts_tests.bzl
- tests/new_sets_tests.bzl
- tests/partial_tests.bzl
- tests/paths_tests.bzl
- tests/selects_tests.bzl
- tests/sets_tests.bzl
- tests/shell_tests.bzl
- tests/structs_tests.bzl
- tests/types_tests.bzl
- tests/versions_tests.bzl
Buildifier 0.12.0 includes initial support for reformatting .bzl files.
- Reformat all the bzl files.
- Expand the travis check to check the .bzl files also.
> Reformat .bzl files with buildifier and add format check.

- README.md
- tests/collections_tests.bzl
- tests/dicts_tests.bzl
- tests/new_sets_tests.bzl
- tests/partial_tests.bzl
- tests/paths_tests.bzl
- tests/selects_tests.bzl
- tests/sets_tests.bzl
- tests/shell_tests.bzl
- tests/structs_tests.bzl
- tests/types_tests.bzl
- tests/versions_tests.bzl
As more things are added, lib.bzl is an anti-pattern as the cost of loading
it actually just keeps increasing and most things will never use everything
out of it.  The pattern the should be used is to directly import the modules
one uses.
> Remove usage and suggests for lib.bzl.

- BUILD
- lib.bzl
- tag the :lib target as such.
- print() a warning when lib.bzl is loaded.
> deprecate lib.bzl.

- BUILD
- README.md
- bzl_library.bzl
- lib/BUILD
- lib/partial.bzl
- lib/selects.bzl
- lib/unittest.bzl
- skylark_library.bzl
- starlark_library.bzl
- tests/selects_tests.bzl
Most notably, this renames/moves a few important identifiers:
//:skylark_library.bzl -> //:starlark_library.bzl
skylark_library -> starlark_libary
SkylarkLibraryInfo -> StarlarkLibraryInfo
> Rename a number of instances of 'skylark' to 'starlark'

- lib/versions.bzl
The fail() and print() primitives take strings without newlines in them
because the formatted output will already contain newlines.  Therefore,
remove them, which have been annoying me to no end when using rules_go
with a HEAD-built Bazel binary.
While doing this, also switch to using .format() consistently for all
strings, merge two related debug messages into the same print() call,
and fix grammar.
> Remove spurious newlines from fail/print messages

- lib/sets.bzl
Make _precondition_only_sets_or_lists in sets.bzl not assume type() is string
Such an assumption makes this check brittle in the face of potential future changes to type().
types.bzl was not used to keep sets.bzl independent as well as types.bzl does not currently support depsets
> Make _precondition_only_sets_or_lists in sets.bzl not assume type() is str

- skylark_library.bzl
Update skylark_library.bzl to conform to Google's code style
Even though skylark_library.bzl is deprecated, it should still conform to Google's code style.
> Update to google style

- tests/new_sets_tests.bzl
With `--incompatible_depset_is_not_iterable` depset is no longer
iterable. Remove tests that assumed it is.
Bazel issue:
https://github.com/bazelbuild/bazel/issues/5816
> Remove support for make(depset()) from new_sets

- lib/unittest.bzl
- tests/selects_tests.bzl
Fixes some dict order issues with the current version of buildifier.
> Run buildifier --lint=fix over the files.

- rules/BUILD
- rules/build_test.bzl
- rules/empty_test.sh
- tests/BUILD
- tests/build_test_tests.bzl
This rules (marco) provides a 'test' target that can be used to ensure other
targets build.
> Add a build_test rule.

- lib/unittest.bzl
- tests/BUILD
- tests/unittest_test.sh
- tests/unittest_tests.bzl
This framework allows for easy creation of unittest-like tests to make assertions
on the provider-values returned by real targets.
Extensive documentation (in the form of updating the repository README) to follow in a future PR
> Add analysis-test test framework

- .bazelci/presubmit.yml
- rules/analysis_test.bzl
- tests/BUILD
- tests/analysis_test_test.sh
Add analysis_test rule
Targets of this rule verify that targets can be analyzed successfully.
This is similar to build_test, except no actual action execution of
the underlying targets occur. analysis_test essentially verifies that
`bazel build [targets] --nobuild` passes.
> Add analysis_test rule

- .bazelci/presubmit.yml
"buildifier: true" has been deprecated by https://github.com/bazelbuild/continuous-integration/pull/542
> Fix Buildifier version

- docs/BUILD
- rules/BUILD
- rules/copy_file.bzl
- rules/copy_file_private.bzl
- tests/BUILD
- tests/copy_file/BUILD
- tests/copy_file/a.txt
- tests/copy_file/copy_file_tests.sh
This PR adds two new rules: copy_file and
copy_xfile.
Both rules solve a common problem: to copy one
file to another location. The problem is routinely
solved using a genrule. That however requires
Bash, since genrules execute Bash commands.
Requiring Bash is a problem on Windows.
The new rules do not require Bash on Windows (only
on other platforms).
The only difference between the rules is that
copy_xfile creates an executable file while
copy_file doesn't.
See https://github.com/bazelbuild/bazel/issues/4319
> copy_file: add rule and tests

- rules/private/write_file_private.bzl
- tests/selects_tests.bzl
Fixes some dictionaries to put things in the more common orders. Buildifer
used to default to doing this check and reformatting which is why the
//conditions:default got moved up in these in the first place.
> Reformat with buildifier --warnings=all

- lib/unittest.bzl
This allows `analysistest.make` rules to be parameterized.
> Pass through an attribute arguments to `analysistest.make`.

- docs/write_file_doc.md
- rules/private/write_file_private.bzl
- tests/write_file/BUILD
The user can specify which line endings they want
write_file to use. This helps avoiding line ending
mismatches with diff_test.
Example: diff_test verifies that a rule generates
correct output by comparing it to a checked-in
"golden" file. Both files are text files, and the
user builds on Windows but the golden file was
written on Linux and git checkout preserved
original line endings.
Without explicitly specifying which line endings
to use, this diff_test would fail on an otherwise
good output.
With explicit line endings we don't need to check
in the golden file to git, we can just generate it
with "auto" line endings.
> write_file: support different line endings

- rules/private/copy_file_private.bzl
I plan to use these functions in native_binary()
and native_test().
See https://github.com/bazelbuild/bazel-skylib/issues/148
> copy_file: expose the copying logic

- lib/sets.bzl
- lib/unittest.bzl
- tests/BUILD
- tests/old_sets_tests.bzl
Make sets.bzl point to new_sets.bzl instead of old_sets.bzl
new_sets.bzl and old_sets.bzl should be removed in the following skylib release.
Fixes #155.
> Make sets.bzl point to new_sets.bzl instead of old_sets.bzl

- WORKSPACE
- lib/selects.bzl
- Update to newer version of stardoc.
- Make lib/selects.bzl stardoc compatible. There must be a block description before Args:
Docs now generate with
bazel build --incompatible_remap_main_repo docs:*
See https://github.com/bazelbuild/bazel/issues/7130 for reasons.
> Get docs working again.

- lib/selects.bzl
There might be other attributes of config_setting you want to expose. I didn't want to do a general kwargs since this is using alias underneath and that might allow leaking attributes you don't want the macro to support.
> Make config_setting_group visibility aware

- WORKSPACE
- internal_deps.bzl
- internal_setup.bzl
This commit allows bazel_skylib to be a member of the Bazel federation, since it adds the required bzl files related to setup and dependencies.
Moreover, it also changes the WORKSPACE to fetch all dependencies through the federation.
> Comply with the standards of the Bazel federation

- WORKSPACE
We need to use maybe() for federation, so we can try updates to the federation that impact how skylib loads.  All mutually recursive repos should use maybe to make this possible.
> load rules thorugh maybe so we can simultaneous updates

- WORKSPACE
- distribution/BUILD
Part of #198 
The complete fix is would require bazel-skylib -> @bazel_skylib remapping 
- to wait for https://github.com/bazelbuild/rules_pkg/pull/99 to work its way into the next rules_pkg release
- then wait for that to make it to a federation release
- then update to that federation release
> Fix distribution so that we get the right dependencies load

- lib/unittest.bzl
- tests/unittest_tests.bzl
genfiles_dir has been the same as bin_dir for several Bazel releases, and is
being fully removed in upcoming Bazel release.
> Remove genfiles_dir retrieval method

- BUILD
- distribution/BUILD
- rules/BUILD
This is super ugly, but it gets the permissions right
diff /tmp/tar.1 /tmp/tar.2
1a2,3
> drwxr-xr-x 0/0               0 1999-12-31 19:00 ./rules/
> -r-xr-xr-x 0/0             103 1999-12-31 19:00 ./rules/empty_test.sh
3c5
< -r--r--r-- 0/0            1514 1999-12-31 19:00 ./BUILD
---
> -r--r--r-- 0/0            1591 1999-12-31 19:00 ./BUILD
19c21
< -r--r--r-- 0/0           18109 1999-12-31 19:00 ./lib/unittest.bzl
---
> -r--r--r-- 0/0           17682 1999-12-31 19:00 ./lib/unittest.bzl
21,22c23
< drwxr-xr-x 0/0               0 1999-12-31 19:00 ./rules/
< -r--r--r-- 0/0            1309 1999-12-31 19:00 ./rules/BUILD
---
> -r--r--r-- 0/0            1448 1999-12-31 19:00 ./rules/BUILD
28d28
< -r--r--r-- 0/0             103 1999-12-31 19:00 ./rules/empty_test.sh
> Fix execute bit on empty_test.sh

- README.md
This pair of rules was removed in 58068fe0cc28d8d5e0115bf0e7d80189628f35db, and the docs removed in 084758ff75463750f6c2476348ed9442e7860275 - the links were forgotten.
> Remove links to maprules

- .bazelci/presubmit.yml
It's on by default since Bazel 2.0, and the flag is now going away.
https://github.com/bazelbuild/bazel/issues/7130
> Remove flag --incompatible_remap_main_repo

- lib/selects.bzl
- tests/selects_tests.bzl
Specifically:
```
selects.config_setting_group(
name = "always_true",
match_any = ["//conditions:default"],
)
```
and
```
selects.config_setting_group(
name = "always_true",
match_all = ["//conditions:default"],
)
```
These should, as expected, always evaluate to True.
Their implementation had a bug that failed the build outright.
> Fix type parsing errors on "always true" conditions.

- BUILD
- lib/BUILD
- rules/BUILD
Stardoc needs access to a file (with exports_files) in order to
generate its documentation.
> Update visibility of files

- docs/BUILD
- tests/common_settings_test.sh
Deprecating this flag so removing all usage.
> Remove --experimental_build_setting_api usage

- WORKSPACE
- while the federation code is in flux, this will mean less churn for skylib
- rules_pkg is only needed by developers for making a distribution, so this won't impact users.
- when we develop a new federation model, we can re-depend the right way.
fixes https://github.com/bazelbuild/bazel-federation/issues/117
> Stop depending on rules_pkg through the federation.

- lib/unittest.bzl
Before, when comparing large sets, the message dumped the whole set. Now it additionally prints missing and unexpected elements.
> Prettify failure message of asserts.set_equals.

- tests/unittest_tests.bzl
This should fix some buildkite CI flows, ensuring success of
this test is no longer tied to the current compilation_mode.
It also improves the error message of the offending evaluation.
> Improve inspect_output_dirs_test bin_dir comparison

- CHANGELOG.md
- version.bzl
This is a roll up of changes since 1.0.2.  In spite of a few being labeled incompatible, they are removal of deprecated features that should not break existing users.
> Update version stamp and CHANGELOG for 1.0.3

- docs/new_sets_doc.md
Lists are not supported. The code comments were fixed to match this in http://github.com/bazelbuild/bazel-skylib/commit/2d620ba1f8284695181fa092ec4064724ea99a9a, but the docs were never updated.
> Fix the docs to match the comment and code.

- gazelle/bzl/gazelle.go
- gazelle/bzl/testdata/bazel_tools/BUILD.in
- gazelle/bzl/testdata/bazel_tools/BUILD.out
- gazelle/bzl/testdata/bazel_tools/foo.bzl
`@bazel_tools` is tricky since it is effectively a part of the standard
library that can not have a `bzl_library` attached to it. As a simple
fix for this, `bzl_library` can have a srcs dependency on it so that it
includes the transitive closure of all of its dependencies.
`@bazel_tools` imports are rewritten into the `srcs` attribute since
they are `exports_files`ed from the @bazel_tools.
> Gazelle now handles imports from `@bazel_tools`

- gazelle/bzl/gazelle.go
- gazelle/bzl/testdata/private/nested/private/BUILD.out
- gazelle/bzl/testdata/private/nested/private/bar.bzl
- gazelle/bzl/testdata/private/nested/private/inside/internal/BUILD.out
- gazelle/bzl/testdata/private/nested/private/inside/internal/bar.bzl
Both "internal" and "private" directories should be treated the same way
and have visibility restrictions be placed upon them.
> Handle "internal" directory visibility

- README.md
I'd run across write_file from a Google search, and noticed, while using it, that its docs weren't in the README. 
So I figured I'd toss up a quick PR to add it and it's cousin, copy_file.
The README's list still isn't complete, but it's at least more complete.
> Add write_file and copy_file docs to README

- tests/copy_file/copy_file_tests.sh
- tests/diff_test/diff_test_tests.sh
- tests/write_file/write_file_tests.sh
Prevent Debian's lintian from complaining about scripts without shebangs. There does not seem to be a reason (that I can see) for the shebang being omitted. Since it is present in other shell scripts in the repository, I'm assuming that it's just an oversight that it's missing on these three files.
> Add shebang lines to tests directory shell scripts

- WORKSPACE
- lib/partial.bzl
- lib/structs.bzl
- rules/private/copy_file_private.bzl
- tests/copy_file/BUILD
We should not assume their existence.
Fixes https://github.com/bazelbuild/bazel-skylib/issues/294
> to_json/to_proto methods on structs are deprecated and will be removed

- README.md
See https://github.com/bazelbuild/bazel-skylib/branches and https://github.com/bazelbuild/bazel-skylib/issues/281.
> Fix default branch name in README

- CHANGELOG.md
- docs/build_test_doc.md
- docs/diff_test_doc.md
- docs/native_binary_doc.md
- docs/run_binary_doc.md
- rules/build_test.bzl
- rules/common_settings.bzl
- rules/diff_test.bzl
- rules/native_binary.bzl
- rules/run_binary.bzl
Docs are now served under  docs.bazel.build/versions/main
> update links to bazel docs

- tests/write_file/write_file_tests.sh
Due to grep having dropped support for handling line-ending matches in a cross-platform way, grepping for `...$` will now fail on Windows, as it no longer ignores the CR part of the CRLF line endings on Windows.
This should turn this project green again on Bazel CI.
> Remove `$` from grep regexes

- lib/unittest.bzl
- tests/unittest_tests.bzl
To simulate this in a test I had to define a separate attribute with the
aspect applied and ignore `target_under_test`, except because
`target_under_test` is mandatory I had to set some value for it which
was ignored.
This may or may not fix
https://github.com/bazelbuild/bazel-skylib/issues/189 (I could see also
wanting a `build_test`-like target which builds with an aspect - I'm not
entirely sure what the scope of that issue was meant to be :))
> Allow specifying additional aspects to tut

- rules/BUILD
- rules/build_test.bzl
- rules/empty_test.sh
I have to point out that the approach used in this PR is a bit hacky as it marks `.bat` file as executable on Windows. AFAIK, in order to spawn processes on Windows, Bazel uses `CreateProcessW` function whose [docs](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) says that caller should use `cmd.exe` as the application name and the batch file as one of `lpCommandLine` arguments. On the other hand, I don't know any Windows flavor that wouldn't run the batch file if it's passed as the application name to `CreateProcessW`
> Windows support for build_test

- rules/diff_test.bzl
If `--enable_runfiles` is set, no manifest file will be created, and `RUNFILES_MANIFEST_FILE` will be empty,
but the runfiles will be accessible from the current directory using their canonical names.
If a file cannot be found in the manifest file, check if it can be found relative from pwd.
This is the same logic as in the shell counterpart around line 100.
Fixes #313
> Make diff_test work on windows with --enable_runfiles

- docs/build_test_doc.md
- docs/diff_test_doc.md
- docs/native_binary_doc.md
- docs/run_binary_doc.md
- docs/unittest_doc.md
- lib/unittest.bzl
- tests/unittest_test.sh
- tests/unittest_tests.bzl
- toolchains/unittest/BUILD
daf51370 fixed a bug where the failure message would not be printed
correctly if it included values subject to shell variable expansion
(e.g. "$FOO") by quoting the limit string for the heredoc with the message
("cat <<'EOF'"). However, it still left an issue if that limit string
appeared on its own line in a message, which would happen if a compared
value included "\nEOF\n". (Plausible if the function under test
generated shell script code.) This could be worked around by choosing
a more unusual string, but that remains an odd implementation detail.
Instead, the shell implementation could use the same path of splitting
the output into lines, echoing each line, and backslash-escaping each
character.
The previous code also did not split the error output into lines
correctly if individual …
> Improve escaping in unittest failure message

- docs/unittest_doc.md
- lib/unittest.bzl
- tests/unittest_tests.bzl
This is a relatively simple addition to unittest that statically creates
rules that either explicitly fail or not depending on if the test case is valid during LOADING phase of bazel.  The test conditions are evaluated entirely in loading phase, but if we want an actual test to fail rather than just `fail()` killing the build, we can use this to assert state and report test failures.
> Add support for 'loading' unit tests, which evaluate a LOADING phase.

- docs/unittest_doc.md
- lib/unittest.bzl
I find it more ergonomic to add notes or a description about a test to a `doc` attribute, similar to other rules, vs a comment block above it or in the `impl` function docstring. Hopefully this can improve the readability of test rules.
> Allow unit test rules to be documented

- docs/unittest_doc.md
- lib/unittest.bzl
Same change as https://github.com/bazelbuild/bazel-skylib/pull/351
> Fixed positional args for unittest targets

- BUILD
- distribution/BUILD
- rules/BUILD
//rules:bins has not been used since 14f17ae7f71f347b5e720fca55e33df40bc4e5d5
Alternative to https://github.com/bazelbuild/bazel-skylib/pull/358
> Remove unused, empty //rules:bins filegroup, allowing us to simplify distribution/BUILD

- CHANGELOG.md
- version.bzl
Make a point release to unbreak users who set `--incompatible_disallow_empty_glob`. See discussion in https://github.com/bazelbuild/bazel-skylib/pull/359
> Update changelog and version for release 1.2.1

- tests/unittest.bash
Note that macOS 12.3 removed python2.
> Allow using python3 for timestamps on macOS and BSD

- README.md
- docs/BUILD
- docs/expand_template_doc.md
- rules/BUILD
- rules/expand_template.bzl
- tests/expand_template/BUILD
- tests/expand_template/template_test.sh
- tests/expand_template/test.cc
- tests/expand_template/test.tpl.yaml
- tests/expand_template/version.h.in
Resolves: https://github.com/bazelbuild/bazel-skylib/issues/191
An example of how this can be usefull can be found here: https://github.com/catchorg/Catch2/pull/2387/files
Could be also helpfull here: https://github.com/AcademySoftwareFoundation/openexr/blob/8587f4eed1d396a9c545d59e7b231d9d4b2cd8ef/BUILD.bazel#L21
> Add expand_template rule

- rules/private/copy_file_private.bzl
- rules/private/write_file_private.bzl
copy_file currently includes the copied file in its runfiles even if it is not executable, which makes every rule depending on it have the file as a runfile (e.g. a `cc_library` depending on a copied header file via the hdrs attribute).
In an ideal world, according to https://docs.bazel.build/versions/main/skylark/rules.html#runfiles-features-to-avoid, `copy_file` would not need to specify any runfiles in the `DefaultInfo` it returns - specifying `files` should suffice. However, due to the existence of rules with legacy behavior, this would break compatibility (actually, already with `sh_test` in skylib's unit tests).
As a compromise that preserves compatibility with legacy rules but nevertheless cleans up the runfiles tree of depending rules, use the `data_runfiles` attribute of …
> copy_file: Do not add non-executables to default_runfiles

- rules/private/BUILD
- rules/private/copy_common.bzl
- rules/private/copy_directory_private.bzl
- rules/private/copy_file_private.bzl
@hvadehra This is an optimization we added to our forked versions of copy_directory and copy_file that I forgot to add to the previous PR.
> Use stricter execution requirements for copy actions

- .bazelci/presubmit.yml
- BUILD
- MODULE.bazel
- WORKSPACE
- WORKSPACE.bzlmod
- distribution/BUILD
- docs/analysis_test_doc.md
- docs/build_test_doc.md
- docs/collections_doc.md
- docs/common_settings_doc.md
- docs/copy_directory_doc.md
- docs/copy_file_doc.md
- docs/dicts_doc.md
- docs/diff_test_doc.md
- docs/expand_template_doc.md
- docs/maintainers_guide.md
- docs/native_binary_doc.md
- docs/new_sets_doc.md
- docs/partial_doc.md
- docs/paths_doc.md
- docs/run_binary_doc.md
- docs/selects_doc.md
- docs/shell_doc.md
- docs/structs_doc.md
- docs/subpackages_doc.md
- docs/types_doc.md
- docs/unittest_doc.md
- docs/versions_doc.md
- docs/write_file_doc.md
Creates MODULE.bazel and WORKSPACE.bzlmod files to enable bazel-skylib
to work with the `--experimental_enable_bzlmod` flag.
rules_go has been updated as the previously used version is not
available in the BCR.
stardoc has been updated due to a strange issue with Bzlmod enabled that
caused the `diff_test` and `unittest` docs to be generated without any
contents that was magically fixed upon updating.
bazelbuild/bazel-central-registry#124
> feat: bzlmod setup

- docs/BUILD
- docs/private/stardoc_with_diff_test.bzl
Google internal linters are flagging skylib 1.3.0 because the stardoc_with_diff_test
macro lack a copyright notice and does not use a `name` parameter.
> Fix stardoc_with_diff_test linter warnings

- rules/private/copy_common.bzl
- tests/copy_directory/BUILD.bazel
- tests/copy_directory/empty_directory.bzl
After some thought, I have to say that forcing a local strategy for
copy_file/copy_directory is inappropriate. The point of a sandbox is to
catch hermeticity bugs; disabling the sandbox may be useful for
performance, but it's up to the user to do it if they trust us - and
they can do it via flag. The default should be paranoia and safety.
And on the subject of strategies - using a genrule to create an empty
directory fails in environments where genrules run remote by default
(and thus, copy_directory tests fail). We could, of course, set local=1,
but that disables the sandbox and causes scary warnings. Instead, add a
proper empty_directory rule to test with.
> Allow sandboxing for copy_* and fix copy_directory tests

- rules/common_settings.bzl
By stripping leading '@'s from labels in the main repo. So it talks about the flag '//foo:bar' instead of the flag '@//foo:bar'.
> Make settings error message more friendly

- tests/analysis_test_test.sh
- tests/common_settings_test.sh
- tests/copy_directory/copy_directory_tests.sh
- tests/copy_file/copy_file_tests.sh
- tests/diff_test/diff_test_tests.sh
- tests/expand_template/template_test.sh
- tests/native_binary/assertdata.cc
- tests/unittest_test.sh
- tests/write_file/write_file_tests.sh
bazelbuild/bazel@6a8ddb7 changed the prefix for runfiles from the main repo when Bzlmod is enabled. Because all uses of rlocation were hardcoded to use "bazel_skylib", tests requiring runfiles stopped working with Bzlmod enabled. This commit updates calls to rlocation to instead use the TEST_WORKSPACE env var to get the repo name.
> Stop hardcoding runfiles prefix

- gazelle/MODULE.bazel
I'm not sure if this is the best way to solve this problem, but there are two cases where we want to use this repo:
1/ We're developing the repo itself. We should be responsible for
registering the Go toolchain.
2/ We're being used transitively by another module (eg.
`contrib_rules_jvm`. We should _not_ be responsible for
registering the Go toolchain
Now, in the ideal world, we'd declare the Go SDK as a dev dependency, and everything would be fine. However, we can't do this because there's no way to gate the call to `register_toolchain` on us being the root module or not.
The workaround? Attempt to use a unique name for the Go SDK that we need and hope that this works as we think it does.
> Stop registering a Go SDK in the Gazelle submodule

- .bazelci/presubmit.yml
- MODULE.bazel
- MODULE.bazel-remove-override.patch
- WORKSPACE
- distribution/BUILD
- docs/maintainers_guide.md
- gazelle/BUILD
- gazelle/MODULE.bazel
- gazelle/bzl/BUILD
- version.bzl
After #400, the gazelle plugin has been cleanly separated out into its own bazel workspace, which will soon finally allow us to mark it stable. But this means:
* we need to change our bazelci config to explicitly build and test it, since `bazel build //...` no longer includes the plugin;
* we need to add proper distribution rules for it;
* we need to update release instructions, since now we will have two distribution tarballs
> Add gazelle plugin to CI and distribution mechanism

- BUILD
- CHANGELOG.md
- MODULE.bazel
- README.md
- WORKSPACE
- distribution/BUILD
- distribution/distribution.bzl
- gazelle/BUILD
- gazelle/MODULE.bazel
- version.bzl
* Fix location of MODULE.bazel in distro tarballs.
* Remove invalid paths from WORKSPACE files in distro tarballs
* The resulting tarballs should finally be distributable as 1.4.0 in BCR.
> Fix distribution tarballs and update changelog and version for release 1.4.0

- gazelle/bzl/BUILD
> fix: allow empty glob for `testdata` in the Gazelle extension

- gazelle/MODULE.bazel
- gazelle/workspace.bzl
Partially addresses https://github.com/bazelbuild/bazel-skylib/issues/418
> Update rules_go and gazelle deps to be compatible with --incompatible_disable_starlark_host_transitions

- .bazelci/presubmit.yml
In order to flip the flag, all downstream projects should be adapted. However, it is hard to fix them all if there are constant regressions. Adding it to the CI will ensure that once the project can build with incompatible_disallow_empty_glob it can keep building like that. See: bazelbuild/bazel#15327
> Build with incompatible_disallow_empty_glob

- rules/build_test.bzl
I ran into an issue where I had a `build_test` that was only compatible with a particular platform. I had annotated the target with `target_compatible_with` but continued to get builds on the incompatible platform. This came down to my `bazel test //...` invocation picking up the `{name}_{idx}__deps` targets and building the dependency anyway. This change updates these targets to account for newer common attributes and tags them as manual so they're only built when the user facing test target is built.
> Avoid building build_test deps unnecessarily

- bzl_library.bzl
- docs/BUILD
- docs/bzl_library.md
> Allow .scl files in bzl_library

- CHANGELOG.md
- MODULE.bazel
- WORKSPACE
- gazelle/MODULE.bazel
- version.bzl
This should be applied *after* #450 is merged.
> Update changelog and version for release 1.4.2

- docs/common_settings_doc.md
- rules/common_settings.bzl
- tests/BUILD
- tests/common_settings/BUILD
- tests/common_settings/make_variable_test.sh
- tests/common_settings_tests.bzl
- tests/subpackages_tests.bzl
While build settings allow for much cleaner flag and setting definitions than `--define`, they have the major drawback that rules need to provide dedicated support for them, which isn't the case for native and most community-maintained rules.
This change attempts to bridge this gap by optionally exposing the value of the common build setting types as Make variables to rules that depend on them via the `toolchains` attribute: If the new `make_variable` attribute is set, the value of the flag or setting is available as a Make variable with that.
Consistency with pre-defined Make variables is enforced by limiting the character set for `make_variable` values to `[A-Z0-9_]`. The new attribute is also only added to int- and string-valued build settings as the other types lack a canonical …
> Expose int- and string-valued build settings as Make variables

- distribution/BUILD
- docs/private/stardoc_with_diff_test.bzl
- gazelle/workspace.bzl
- rules/private/copy_file_private.bzl
- rules/run_binary.bzl
- tests/build_test_tests.bzl
- tests/native_binary/BUILD
- tests/run_binary/BUILD
- tests/select_file/BUILD
- tests/types_tests.bzl
All actions which use tool or executable for which is not clear if it comes from a toolchain, must set a `toolchain` parameter ( migration of Automatic Exec Groups). 
As we discussed internally, I've modified actions so that it's recognised that tools are not from the toolchain. Hence, there will not be an error which states `Couldn't identify if tools are from implicit dependencies or a toolchain. Please set the toolchain parameter. If you're not using a toolchain, set it to 'None'.`. Hence, no need for the toolchain parameter.
> Modify actions in order not to need `toolchain` param 

- docs/versions_doc.md
- lib/versions.bzl
- tests/versions_tests.bzl
Dev builds of Bazel are assumed to be more recent than any released version.
> versions: Don't fail on Bazel dev builds

- bzl_library.bzl
This improves the error in the case your bzl_library does nothing. Otherwise you end up with something weirder later:
```
BUILD:35:12: in deps attribute of bzl_library rule LABEL: 'DEP' does not produce any bzl_library deps files (expected .bzl)
```
Ideally we could set `allow_empty = False` on `srcs` but currently it's valid to just have a bzl_library target that aggregates multiple other libraries in its deps.
> Add error for empty bzl_library

- docs/unittest_doc.md
- lib/unittest.bzl
Same change as https://github.com/bazelbuild/bazel-skylib/pull/343 but now for `unittest`
> Add `doc` param to `unittest.make`

- gazelle/MODULE.bazel
- gazelle/setup.bzl
- gazelle/workspace.bzl
This fixes building bazel-skylib at head with Bazel at head.
Fixes: https://github.com/bazelbuild/bazel-skylib/issues/459
> Upgrade rules_go

- docs/unittest_doc.md
- lib/unittest.bzl
Make unittests.make bypass toolchains argument to target rule's constructor.
> Add toolchains argument to unittests.make

- tests/common_settings/BUILD
Internal linter complains about lack of license info.
> Add licenses spec to new BUILD file

- rules/expand_template.bzl
output_to_genfiles is deprecated unless needed for backwards compatibility with legacy rules (see https://bazel.build/rules/lib/globals/bzl#rule)
> expand_template: do not output_to_genfiles

- MODULE.bazel
- WORKSPACE
- tests/build_test_tests.bzl
- tests/native_binary/BUILD
- tests/run_binary/BUILD
Fixes #475 
^ please see that issue for context before reading :)
> Remove outdated rules_cc dependency

- docs/modules_doc.md
- lib/modules.bzl
WORKSPACE macros are fully deterministic and thus a prime example of a `reproducible` module extension. This reduces clutter in `MODULE.bazel.lock`.
> Mark `modules.as_extension` as `reproducible`

- lib/modules.bzl
In Bazel 6, the doc parameter of the module_extension function doesn’t accept None; cf. https://bazel.build/versions/6.5.0/rules/lib/globals#module_extension vs. https://bazel.build/versions/7.0.0/rules/lib/globals/bzl#module_extension. Instead of passing None in that case, just don’t pass the argument at all and use the respective default.
> Improve compatibility with Bazel 6.

- .bazelci/presubmit.yml
Adding tests with Bazel 5 and 6 will let us catch problems like #499; and Ubuntu 18.04 is getting old
> Improve CI setup: add tests for Bazel 5.x and 6.x (with and without bzlmod); use Ubuntu 20.04 as main platform

- BUILD
- distribution/BUILD
- docs/BUILD
- docs/private/BUILD
- gazelle/BUILD
- lib/BUILD
- rules/BUILD
- rules/private/BUILD
- tests/BUILD
- tests/bzl_library/BUILD
- tests/common_settings/BUILD
- tests/copy_directory/BUILD.bazel
- tests/copy_file/BUILD
- tests/diff_test/BUILD
- tests/select_file/BUILD
- tests/write_file/BUILD
- toolchains/unittest/BUILD
And take the opportunity to fix default_applicable_licenses in the gazelle plugin
> Re-add `licenses()` - internal license checker still requires it :/

- .gitignore
I would add --lockfile_mode=off to .bazelrc, but this should support older versions of bazel before the lockfile_mode flag was released.
> Add MODULE.bazel.lock to gitignore.

- docs/paths_doc.md
- lib/paths.bzl
- tests/paths_tests.bzl
Those two functions are often used by built-in rules. This will make it easier to move them out of Bazel binary.
> Add is_normalized and starts_with to paths module

- rules/directory/directory.bzl
- tests/directory/external_directory_tests.bzl
Previously, I was getting the error
`Expected external/_main~toolchains~toolchain_sdk/usr/bin/clang++ to start with one of ["external/_main~toolchains~toolchain_sdk//", "bazel-out/k8-dbg/bin/external/_main~toolchains~toolchain_sdk/"]`
> fix: Ensure directories work when the package is empty

- rules/directory/private/glob.bzl
- tests/directory/glob_test.bzl
For example, if you try to match `*a*" against "ab", then we check:
```
left = ""
middle = "a"
right = ""
middle in name[len(left):len(name)-len(right)]:
"a" in "ab"[len(""):len(name)-len("")]:
"a" in "ab"[0:-0]
"a" in "" => False
```
The problem here is that negative numbers in python index from the back, but -0 is not a negative number, so it always results in the empty string.
> fix: Fix a bug in globs when middle is non-empty, but right is empty.

- lib/subpackages.bzl
This fixes "subpackages.all" which delivers broken results in case it is used in the root package.
Assuming there is a package `//foo`. Then `subpackages.all` returns `["///foo"]`. With this fix it return the expected `["//foo"]`.
> fix: subpackages.all works for root packages

- BUILD
- bzl_library.bzl
- docs/BUILD
- rules/private/BUILD
- rules/private/bzl_library.bzl
Wrap bzl_library in a macro so that we can force off some global attributes that are never appropriate for analysis of build rules.
The motivation is that when people use `package(default_compatible_with=X)` alongside `bzl_library`, they have accidentally marked their _build rules_ as eligible to deliver to some target environment. This can cause `...` scoped tests on cross platform projects to fail because the user defined rules are not the code we are shipping.
An alternative idea was to use a rule initializer for this. That is the better solution, but it would require a newer version of Bazel, so I opted for the backwards compatible solution.
> Strip compatible_with from bzl_library rules

- lib/BUILD
- rules/BUILD
- toolchains/unittest/BUILD
All other test_deps targets implicitly require the root BUILD file for the `license` target for their default_applicable_licenses; therefore, users should only depend on the root test_deps target.
> Make only root test_deps externally visible

- rules/native_binary.bzl
Bazel 4.x support has ended with https://github.com/bazelbuild/bazel-skylib/releases/tag/1.2.1.
> Remove obsolete bazel 4.x compat code

- docs/native_binary_doc.md
- rules/native_binary.bzl
- tests/native_binary/BUILD
- tests/native_binary/assertenv.cc
This (standard) variable "env" allows the propagation of environment variables to the test being executed or tested.
> Add new "env" variable to native_* rules

- rules/private/BUILD
- rules/private/copy_common.bzl
- rules/private/copy_directory_private.bzl
- rules/private/copy_file_private.bzl
> Migrate `copy_directory` away from deprecated host constraint
